Correct reactive error handling in UniDataFetcher
smallrye/smallrye-graphql pull request #653
Opened 2021-02-24 17:30 UTC by Andro999b

fix for https://github.com/quarkusio/quarkus/issues/15271

2021-02-24 20:21 UTC, cescoffier submitted a review, later dismissed
The mutiny part is good.

When the function was throwing an exception, mutiny created a composite exception with the original failure and the thrown exception.

2021-02-25 06:26 UTC, phillip-kruger requested changes
Nice !! Thanks very much @Andro999b . One small change and maybe you can add a test in the TCK module ?

Java code here: https://github.com/smallrye/smallrye-graphql/blob/master/server/tck/src/test/java/io/smallrye/graphql/test/apps/error/api/ErrorApi.java

And graphQL query here: https://github.com/smallrye/smallrye-graphql/tree/master/server/tck/src/test/resources/tests/errors

Thanks !

2021-02-25 06:26 UTC, phillip-kruger commented on server/implementation/src/test/java/io/smallrye/graphql/execution/ExecutionTestBase.java
> +import javax.json.*;
Keep the imports specific (as it was)

2021-02-25 09:04 UTC, phillip-kruger approved these changes
Thanks @Andro999b !!!

2021-02-25 09:05 UTC, phillip-kruger commented
@Andro999b - Thanks for this. Can you please also add this to the 1.0.x branch (master  is 1.1.x that has not yet been included in any runtime, it's waiting for MP4) 1.0.x is the version currently in Quarkus

2021-02-25 09:05 UTC, merged